# Set base image
FROM node:16-alpine3.16

# Create a non-root user and group
RUN addgroup -S backend-app-group && adduser -S backenduser -G backend-app-group

# Set the working directory and change ownership to the non-root user
WORKDIR /backend
RUN chown backenduser:backend-app-group /backend

# Switch to the non-root user
USER backenduser

# Copy package.json and package-lock.json to the container
COPY --chown=backenduser:backend-app-group package*.json ./

# Install dependencies and clears the npm cache and removes any temporary files
RUN npm install --only=production && \
    npm cache clean --force && \
    rm -rf /tmp/*

# Copy the rest of the application code, ensuring the correct ownership
COPY --chown=backenduser:backend-app-group . .

# Set the environment variable for the app
ENV NODE_ENV=production

# Expose the port used by the app
EXPOSE 5000

# Prune the node_modules directory to remove development dependencies and clears the npm cache and removes any temporary files
RUN npm prune --production && \
    npm cache clean --force && \
    rm -rf /tmp/*

# Start the application
CMD ["npm", "start"]