---
- name: Pull image from repository
  docker_image:
    name: chriskilelo/chris-yolo-backend:v1.0.1
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: chris-yolo-backend
    image: chriskilelo/chris-yolo-backend:v1.0.1
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes