apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: chris-yolo-client
          image: chriskilelo/chris-yolo-client:v1.0.4
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017"